app/beer/urls.py
from django.urls import path

from . import views

app_name = "beer"

urlpatterns = [
    path("", views.BeerList.as_view(), name="beer_list"),
    path("<int:pk>/", views.BeerDetail.as_view(), name="beer_detail"),
    path("<int:pk>/create/", views.BeerCreate.as_view(), name="beer_create"),
    path("<int:pk>/image/", views.ImageCreate.as_view(), name="image_create"),
    path("<int:pk>/review/", views.ReviewCreate.as_view(), name="review_create"),
    path("<int:pk>/favorite/", views.favorite, name="favorite"),
]

app/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path("", include("index.urls"), name="index"),
    path("admin/", admin.site.urls),
    path("beer/", include("beer.urls"), name="beer"),
    path("brewery/", include("brewery.urls"), name="brewery"),
    path("location/", include("location.urls"), name="location"),
    path("user/", include("user.urls"), name="user"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Brews and Beers Admin"
admin.site.site_title = "Brews and Beers"
admin.site.index_title = "Admin Dashboard"

app/location/urls.py
from django.urls import path

from . import views

app_name = "location"

urlpatterns = [
    path("<int:pk>/", views.LocationDetail.as_view(), name="location_detail"),
    path("<int:pk>/create/", views.LocationCreate.as_view(), name="location_create"),
    path("<int:pk>/image/", views.ImageCreate.as_view(), name="image_create"),
    path("<int:pk>/review/", views.ReviewCreate.as_view(), name="review_create"),
]

app/user/urls.py
from django.urls import path

from . import views

app_name = "user"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("password_reset", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("<int:pk>/", views.UserDetail.as_view(), name="user_detail"),
]

app/user/views.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, TemplateView

from beer.models import BeerReview, Favorite
from location.models import LocationReview


class RegisterView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("user:login")
    template_name = "user/register.html"


class LoginView(auth_views.LoginView):
    template_name = "user/login.html"


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """No modification required as long as LOGOUT_REDIRECT_URL is set in settings"""


class PasswordResetView(auth_views.PasswordResetView):
    email_template_name = "user/password_reset_email.html"
    subject_template_name = "user/password_reset_subject.txt"
    success_url = reverse_lazy("user:password_reset_done")
    template_name = "user/password_reset_form.html"


class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = "user/password_reset_done.html"


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    success_url = reverse_lazy("user:password_reset_complete")
    template_name = "user/password_reset_confirm.html"


class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = "user/password_reset_complete.html"


class PasswordChangeView(LoginRequiredMixin, auth_views.PasswordChangeView):
    success_url = reverse_lazy("user:password_change_done")
    template_name = "user/password_change_form.html"


class PasswordChangeDoneView(LoginRequiredMixin, auth_views.PasswordChangeDoneView):
    template_name = "user/password_change_done.html"


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "user/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["beer_reviews"] = BeerReview.objects.filter(user=self.request.user)
        context["location_reviews"] = LocationReview.objects.filter(
            user=self.request.user,
        )
        context["favorites"] = Favorite.objects.filter(user=self.request.user)
        return context


class UserDetail(DetailView):
    model = User
    template_name = "user/user_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["beer_reviews"] = BeerReview.objects.filter(user_id=self.kwargs["pk"])
        context["location_reviews"] = LocationReview.objects.filter(
            user_id=self.kwargs["pk"],
        )
        context["favorites"] = Favorite.objects.filter(user_id=self.kwargs["pk"])
        return context

app/user/templates/user/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}

{% block content %}
  <div class="container">
    <form class="row gy-2 gx-3 align-items-center w-25 p-3" method="post">
      <h1>Login</h1>

      {% csrf_token %}

      <div class="form-floating">
        <input type="text" class="form-control" name="username" placeholder="Username">
        <label for="floatingInput">Username</label>
      </div>

      <div class="form-floating">
        <input type="password" class="form-control" name="password" placeholder="Password">
        <label for="floatingPassword">Password</label>
        <br>
        <input type="submit" class="btn btn-primary mb-3" value="Login">
      </div>

      <p><a href="{% url 'user:register' %}">Register</a></p>
      <p><a href="{% url 'user:password_reset' %}">Reset Password</a></p>
    </form>
  </div>
{% endblock %}

app/user/templates/user/password_change_done.html
{% extends 'base.html' %}

{% block title %}Change Password{% endblock %}

{% block content %}
  <h1>Change Password</h1>
  <p>Your password has been updated.</p>
{% endblock %}

app/user/templates/user/password_change_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Change Password{% endblock %}

{% block content %}
  <div class="container">
    <h1>Change Password</h1>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Change Password">
    </form>
  </div>
{% endblock %}

app/user/templates/user/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}Password Reset{% endblock %}

{% block content %}
  <h1>Password Reset</h1>
  <p>Your password has been reset.</p>
{% endblock %}

app/user/templates/user/password_reset_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Password Reset{% endblock %}

{% block content %}
  <div class="container">
    <h1>Password Reset Confirm</h1>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Confirm">
    </form>
  </div>
{% endblock %}

app/user/templates/user/password_reset_done.html
{% extends 'base.html' %}

{% block title %}Password Reset{% endblock %}

{% block content %}
  <h1>Password Reset</h1>
  <p>A password reset link has been sent to the email address you provided.</p>
{% endblock %}

app/user/templates/user/password_reset_email.html
A password reset request was submitted for email {{ email }}.
Follow the link below to reset your password:
{{ protocol}}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}

app/user/templates/user/password_reset_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Password Reset{% endblock %}

{% block content %}
  <div class="container">
    <h1>Password Reset</h1>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Reset Password">
    </form>
  </div>
{% endblock %}

app/user/templates/user/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
  <div class="container">
    <h1>{{ user.username }}</h1>
    <p><a href="{% url 'user:password_change' %}">Change Password</a></p>

    <h2>Favorites</h2>
    {% if favorites %}
      <ul>
      {% for favorite in favorites %}
        <li><a href="{% url 'beer:beer_detail' favorite.beer.pk %}">{{ favorite.beer.name }}</a></li>
      {% endfor %}
      </ul>
    {% else %}
      <p>You haven't saved any favorites yet.</p>
    {% endif %}

    <h2>Beer Reviews</h2>
    {% if beer_reviews %}
    <ul>
      {% for review in beer_reviews%}
        <li><a href="{% url 'beer:beer_detail' review.beer.pk %}">{{ review.beer.name }}</a></li>
      {% endfor %}
    </ul>
    {% endif %}

    <h2>Location Reviews</h2>
    {% if location_reviews %}
    <ul>
      {% for review in location_reviews%}
        <li><a href="{% url 'location:location_detail' review.location.pk %}">{{ review.location.brewery.name }} in {{ review.location.city }}</a></li>
      {% endfor %}
    </ul>
    {% endif %}
  </div>
{% endblock %}

app/user/templates/user/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Register{% endblock %}

{% block content %}
  <div class="container">
    <h1>Register</h1>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Register">
    </form>
  </div>
{% endblock %}

app/user/templates/user/user_detail.html
{% extends 'base.html' %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <div class="container">
    <h1>{{ user.username }}</h1>

    <h2>Favorites</h2>
    {% if favorites %}
      <ul>
      {% for favorite in favorites %}
        <li><a href="{% url 'beer:beer_detail' favorite.beer.pk %}">{{ favorite.beer.name }}</a></li>
      {% endfor %}
      </ul>
    {% else %}
      <p>{{ user.username }} hasn't saved any favorites yet.</p>
    {% endif %}

    <h2>Beer Reviews</h2>
    {% if beer_reviews %}
    <ul>
      {% for review in beer_reviews%}
        <li><a href="{% url 'beer:beer_detail' review.beer.pk %}">{{ review.beer.name }}</a></li>
      {% endfor %}
    </ul>
    {% else %}
      <p>{{ user.username }} hasn't reviewed any beers yet.</p>
    {% endif %}

    <h2>Location Reviews</h2>
    {% if location_reviews %}
    <ul>
      {% for review in location_reviews%}
        <li><a href="{% url 'location:location_detail' review.location.pk %}">{{ review.location.brewery.name }} in {{ review.location.city }}</a></li>
      {% endfor %}
    </ul>
    {% else %}
      <p>{{ user.username }} hasn't reviewed any locations yet.</p>
    {% endif %}
  </div>
{% endblock %}