app/beer/urls.py
from django.urls import path

from . import views

app_name = "beer"

urlpatterns = [
    path("", views.BeerList.as_view(), name="beer_list"),
    path("<int:pk>/", views.BeerDetail.as_view(), name="beer_detail"),
    path("<int:pk>/create/", views.BeerCreate.as_view(), name="beer_create"),
    path("<int:pk>/image/", views.ImageCreate.as_view(), name="image_create"),
    path("<int:pk>/review/", views.ReviewCreate.as_view(), name="review_create"),
    path("<int:pk>/favorite/", views.favorite, name="favorite"),
]

app/brewery/urls.py
from django.urls import path

from . import views

app_name = "brewery"

urlpatterns = [
    path("", views.BreweryList.as_view(), name="brewery_list"),
    path("<int:pk>/", views.BreweryDetail.as_view(), name="brewery_detail"),
    path("create/", views.BreweryCreate.as_view(), name="brewery_create"),
    path("<int:pk>/image/", views.ImageCreate.as_view(), name="image_create"),
]

app/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path("", include("index.urls"), name="index"),
    path("admin/", admin.site.urls),
    path("beer/", include("beer.urls"), name="beer"),
    path("brewery/", include("brewery.urls"), name="brewery"),
    path("location/", include("location.urls"), name="location"),
    path("user/", include("user.urls"), name="user"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Brews and Beers Admin"
admin.site.site_title = "Brews and Beers"
admin.site.index_title = "Admin Dashboard"

app/location/urls.py
from django.urls import path

from . import views

app_name = "location"

urlpatterns = [
    path("<int:pk>/", views.LocationDetail.as_view(), name="location_detail"),
    path("<int:pk>/create/", views.LocationCreate.as_view(), name="location_create"),
    path("<int:pk>/image/", views.ImageCreate.as_view(), name="image_create"),
    path("<int:pk>/review/", views.ReviewCreate.as_view(), name="review_create"),
]

app/brewery/models.py
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from core.models import BaseModel


class Brewery(BaseModel):
    name = models.CharField(max_length=256, unique=True)
    founded = models.IntegerField(
        validators=[
            MinValueValidator(1829),  # Yuengling founded in 1829
            MaxValueValidator(datetime.date.today().year),
        ],
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "breweries"


class Image(BaseModel):
    brewery = models.ForeignKey(Brewery, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/brewery/")

    def __str__(self):
        return f"{self.brewery.name}"

app/brewery/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
)

from .models import Brewery, Image
from beer.models import Beer
from location.models import Location


class BreweryList(ListView):
    model = Brewery
    template_name = "brewery/brewery_list.html"


class BreweryDetail(DetailView):
    model = Brewery
    template_name = "brewery/brewery_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["beers"] = Beer.objects.filter(brewery=self.get_object())
        context["images"] = Image.objects.filter(brewery=self.get_object())
        context["locations"] = Location.objects.filter(brewery=self.get_object())
        return context


class BreweryCreate(LoginRequiredMixin, CreateView):
    model = Brewery
    template_name = "brewery/brewery_create.html"
    fields = [
        "name",
        "founded",
    ]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("brewery:brewery_detail", kwargs={"pk": self.object.pk})


class ImageCreate(LoginRequiredMixin, CreateView):
    model = Image
    template_name = "brewery/image_create.html"
    fields = [
        "image",
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["brewery"] = Brewery.objects.get(pk=self.kwargs["pk"])
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.brewery = Brewery.objects.get(pk=self.kwargs["pk"])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            "brewery:brewery_detail",
            kwargs={"pk": self.object.brewery.pk},
        )

app/brewery/templates/brewery/brewery_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create{% endblock %}

{% block content %}
  <div class="container">
    <h1>Create</h1>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Create">
    </form>
  </div>
{% endblock %}

app/brewery/templates/brewery/brewery_detail.html
{% extends "base.html" %}

{% block title %}{{ brewery.name }}{% endblock %}

{% block content %}
  <div class="container">
    <h1>{{ brewery.name }}</h1>
    <p>Founded in {{ brewery.founded }}</p>

    <h2>Images</h2>
    {% if images %}
      <p><a href="{% url 'brewery:image_create' brewery.pk %}">Submit an image</a></p>
      {% for image in images %}
        <img src="{{ image.image.url }}" alt="{{ image.brewery.name }}">
      {% endfor %}
    {% else %}
      <p>No images yet. Submit one <a href="{% url 'brewery:image_create' brewery.pk %}">here.</a></p>
    {% endif %}

    <h2>Beers</h2>
    {% if beers %}
      <p><a href="{% url 'beer:beer_create' brewery.pk %}">Submit a beer</a></p>
      <ul>
      {% for beer in beers %}
        <li><a href="{% url 'beer:beer_detail' beer.pk %}">{{ beer.name }}</a></li>
      {% endfor %}
      </ul>
    {% else %}
      <p>No beers yet. Submit one <a href="{% url 'beer:beer_create' brewery.pk %}">here.</a></p>
    {% endif %}

    <h2>Locations</h2>
    {% if locations %}
      <p><a href="{% url 'location:location_create' brewery.pk %}">Submit a location</a></p>
      <ul>
      {% for location in locations %}
        <li><a href="{% url 'location:location_detail' location.pk %}">{{ location.street }} {{ location.city }}, {{ location.state }}</a></li>
      {% endfor %}
      </ul>
    {% else %}
      <p>No locations yet. Add one <a href="{% url 'location:location_create' brewery.pk %}">here.</a></p>
    {% endif %}
  </div>
{% endblock %}

app/brewery/templates/brewery/brewery_image_create.html
{% extends "base.html" %}

{% block title %}{{ brewery.name }}{% endblock %}

{% block content %}
  <h1>{{ brewery.name }}</h1>
  <p>
    Upload an image for <a href="{% url 'brewery:brewery_detail' brewery.pk %}">{{ brewery.name }}</a>
  </p>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_div }}
    <input type="submit" value="Upload">
  </form>
{% endblock %}

app/brewery/templates/brewery/brewery_list.html
{% extends "base.html" %}

{% block title %}Breweries{% endblock %}

{% block content %}
  <div class="text-secondary text-center mb-5">
    <div>
      <h1 class="display-5 fw-bold text-dark">Breweries</h1>
      <div class="col-lg-6 mx-auto">
        <p class="fs-5">Can't find what you're looking for?</p>
        <a class="btn btn-warning" href="{% url 'brewery:brewery_create' %}">Add it here</a>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row row-cols-1 row-cols-md-5 g-4">
    {% for brewery in brewery_list %}
      <div class="col">
        <div class="card">
          <img src="https://placehold.co/600x600" alt="{{ brewery.name }}">
          <div class="card-body">
            <h5 class="card-title"><a href="{% url 'brewery:brewery_detail' brewery.pk %}" class="text-secondary text-decoration-none">{{ brewery.name }}</a></h5>
            <p class="card-text text-body-secondary">Founded {{ brewery.founded }} in City, State</p>
          </div>
          <div class="card-footer">
            <small class="text-body-secondary">10 beers with an average rating of 4.5</small>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
{% endblock %}

app/brewery/templates/brewery/brewery_location_review_create.html
{% extends "base.html" %}

{% block title %}{{ brewery.name }}{% endblock %}

{% block content %}
  <h1>{{ brewery.name }}</h1>
  <p>
    Review <a href="{% url 'brewery:brewery_detail' brewery.pk %}">{{ brewery.name }}</a> in {{ brewery_location.city }}, {{ brewery_location.state }}
  </p>
  <form method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <input type="submit" value="Submit">
  </form>
{% endblock %}

app/brewery/templates/brewery/image_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ brewery.name }}{% endblock %}

{% block content %}
  <div class="container">
    <h1>{{ brewery.name }}</h1>
    <p>
      Upload an image for <a href="{% url 'brewery:brewery_detail' brewery.pk %}">{{ brewery.name }}</a>
    </p>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Upload">
    </form>
  </div>
{% endblock %}