app/beer/urls.py
from django.urls import path

from . import views

app_name = "beer"

urlpatterns = [
    path("", views.BeerList.as_view(), name="beer_list"),
    path("<int:pk>/", views.BeerDetail.as_view(), name="beer_detail"),
    path("<int:pk>/create/", views.BeerCreate.as_view(), name="beer_create"),
    path("<int:pk>/image/", views.ImageCreate.as_view(), name="image_create"),
    path("<int:pk>/review/", views.ReviewCreate.as_view(), name="review_create"),
    path("<int:pk>/favorite/", views.favorite, name="favorite"),
]

app/brewery/urls.py
from django.urls import path

from . import views

app_name = "brewery"

urlpatterns = [
    path("", views.BreweryList.as_view(), name="brewery_list"),
    path("<int:pk>/", views.BreweryDetail.as_view(), name="brewery_detail"),
    path("create/", views.BreweryCreate.as_view(), name="brewery_create"),
    path("<int:pk>/image/", views.ImageCreate.as_view(), name="image_create"),
]

app/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path("", include("index.urls"), name="index"),
    path("admin/", admin.site.urls),
    path("beer/", include("beer.urls"), name="beer"),
    path("brewery/", include("brewery.urls"), name="brewery"),
    path("location/", include("location.urls"), name="location"),
    path("user/", include("user.urls"), name="user"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Brews and Beers Admin"
admin.site.site_title = "Brews and Beers"
admin.site.index_title = "Admin Dashboard"

app/location/urls.py
from django.urls import path

from . import views

app_name = "location"

urlpatterns = [
    path("<int:pk>/", views.LocationDetail.as_view(), name="location_detail"),
    path("<int:pk>/create/", views.LocationCreate.as_view(), name="location_create"),
    path("<int:pk>/image/", views.ImageCreate.as_view(), name="image_create"),
    path("<int:pk>/review/", views.ReviewCreate.as_view(), name="review_create"),
]

app/user/urls.py
from django.urls import path

from . import views

app_name = "user"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("password_reset", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("<int:pk>/", views.UserDetail.as_view(), name="user_detail"),
]

app/location/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from brewery.models import Brewery
from core.models import BaseModel

TYPES = [
    ("Brewery Only", "Brewery Only"),
    ("Taproom", "Taproom"),
    ("Brewpub", "Brewpub"),
    ("Beer Garden", "Beer Garden"),
    ("Other", "Other"),
]

CAPACITIES = [
    ("< 10", "< 10"),
    ("10-25", "10-25"),
    ("25-50", "25-50"),
    ("50-100", "50-100"),
    ("> 100", "> 100"),
]

DISTRIBUTIONS = [
    ("Cans", "Cans"),
    ("Bottles", "Bottles"),
    ("Kegs", "Kegs"),
    ("Growlers", "Growlers"),
    ("Draft", "Draft"),
    ("Other", "Other"),
]


class Location(BaseModel):
    brewery = models.ForeignKey(Brewery, on_delete=models.CASCADE)
    street = models.CharField(max_length=256)
    city = models.CharField(max_length=256)
    state = models.CharField(max_length=256)
    type = models.CharField(max_length=256, choices=TYPES)
    tours = models.BooleanField()
    capacity = models.CharField(max_length=256, choices=CAPACITIES)
    distribution = models.CharField(max_length=256, choices=DISTRIBUTIONS)

    def __str__(self):
        return f"{self.brewery.name} - {self.city}, {self.state} - {self.pk}"


class LocationImage(BaseModel):
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/location/")

    def __str__(self):
        return f"{self.location.brewery.name} - {self.location.city}"


class LocationReview(BaseModel):
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    text = models.TextField(max_length=4096)
    rating = models.IntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(5),
        ],
    )

    def __str__(self):
        return f"{self.location.brewery.name} by {self.user.username}"

app/location/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView

from .models import Location, LocationImage, LocationReview
from brewery.models import Brewery


class LocationCreate(LoginRequiredMixin, CreateView):
    model = Location
    template_name = "location/location_create.html"
    fields = [
        "street",
        "city",
        "state",
        "type",
        "tours",
        "capacity",
        "distribution",
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["brewery"] = Brewery.objects.get(pk=self.kwargs["pk"])
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.brewery = Brewery.objects.get(pk=self.kwargs["pk"])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("location:location_detail", kwargs={"pk": self.object.pk})


class LocationDetail(DetailView):
    model = Location
    template_name = "location/location_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["brewery"] = Brewery.objects.get(pk=self.object.brewery.pk)
        context["images"] = LocationImage.objects.filter(location=self.get_object())
        context["reviews"] = LocationReview.objects.filter(location=self.get_object())
        context["nearby_locations"] = Location.objects.filter(
            # TODO: get all in same city and state, then all in same state
            #   consider using zip codes and sorting by distance.
            #   The best option is to geolocate address, but that is costly
            # city=self.object.city,
            state=self.object.state,
        ).exclude(pk=self.object.pk)
        return context


class ImageCreate(LoginRequiredMixin, CreateView):
    model = LocationImage
    template_name = "location/image_create.html"
    fields = [
        "image",
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["location"] = Location.objects.get(pk=self.kwargs["pk"])
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.location = Location.objects.get(pk=self.kwargs["pk"])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            "location:location_detail",
            kwargs={"pk": self.object.location.pk},
        )


class ReviewCreate(LoginRequiredMixin, CreateView):
    model = LocationReview
    template_name = "location/review_create.html"
    fields = [
        "text",
        "rating",
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["location"] = Location.objects.get(pk=self.kwargs["pk"])
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.location = Location.objects.get(pk=self.kwargs["pk"])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            "location:location_detail",
            kwargs={"pk": self.object.location.pk},
        )

app/location/templates/location/image_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ location.brewery.name }}{% endblock %}

{% block content %}
  <div class="container">
    <h1>{{ location.brewery.name }}</h1>
    <p>
      <a href="{% url 'brewery:brewery_detail' location.brewery.pk %}">{{ location.brewery.name }}</a> located at
        <a href="{% url 'location:location_detail' location.pk %}">{{ location.street }} {{ location.city }}, {{ location.state }}</a>
    </p>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Upload">
    </form>
  </div>
{% endblock %}

app/location/templates/location/location_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ brewery.name }}{% endblock %}

{% block content %}
  <div class="container">
    <h1>{{ brewery.name }}</h1>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Submit">
    </form>
  </div>
{% endblock %}

app/location/templates/location/location_detail.html
{% extends "base.html" %}

{% block title %}{{ location.brewery.name }}{% endblock %}

{% block content %}
  <div class="container">
    <h1>{{ location.brewery.name }}</h1>
    <p>{{ location.street }} {{ location.city }}, {{ location.state }}</p>
    <p><a href="{% url 'brewery:brewery_detail' location.brewery.pk %}">Back to {{ location.brewery.name }}</a></p>

    <h2>Images</h2>
    {% if images %}
      <p><a href="{% url 'location:image_create' location.pk %}">Submit an image</a></p>
      {% for image in images %}
        <img src="{{ image.image.url }}" alt="{{ location.brewery.name }}">
      {% endfor %}
    {% else %}
      <p>No images yet. Submit one <a href="{% url 'location:image_create' location.pk %}">here.</a></p>
    {% endif %}

    <h2>Reviews</h2>
    {% if reviews %}
      <p><a href="{% url 'location:review_create' location.pk %}">Submit a review</a></p>
      <ul>
      {% for review in reviews %}
        <li>{{ review.rating }} by <a href="{% url 'user:user_detail' review.user.pk %}">{{ review.user.username }}</a> on {{ review.created_at.date }}: {{ review.text }}</li>
      {% endfor %}
      </ul>
    {% else %}
      <p>No reviews yet. Submit one <a href="{% url 'location:review_create' location.pk %}">here.</a></p>
    {% endif %}

    <h2>Nearby Locations</h2>
    {% if nearby_locations %}
      <ul>
      {% for location in nearby_locations %}
        <li><a href="{% url 'location:location_detail' location.pk %}">{{ location.street }} {{ location.city }}, {{ location.state }}</a></li>
      {% endfor %}
      </ul>
    {% else %}
      <p>No nearby locations found. Add one <a href="{% url 'location:location_create' brewery.pk %}">here.</a></p>
    {% endif %}
  </div>
{% endblock %}

app/location/templates/location/review_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ location.brewery.name }}{% endblock %}

{% block content %}
  <div class="container">
    <h1>{{ location.brewery.name }}</h1>
    <p>{{ location.street }} {{ location.city }}, {{ location.state }}</p>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Submit">
    </form>
  </div>
{% endblock %}