app/beer/urls.py
from django.urls import path

from . import views

app_name = "beer"

urlpatterns = [
    path("", views.BeerList.as_view(), name="beer_list"),
    path("<int:pk>/", views.BeerDetail.as_view(), name="beer_detail"),
    path("<int:pk>/create/", views.BeerCreate.as_view(), name="beer_create"),
    path("<int:pk>/image/", views.ImageCreate.as_view(), name="image_create"),
    path("<int:pk>/review/", views.ReviewCreate.as_view(), name="review_create"),
    path("<int:pk>/favorite/", views.favorite, name="favorite"),
]

app/brewery/urls.py
from django.urls import path

from . import views

app_name = "brewery"

urlpatterns = [
    path("", views.BreweryList.as_view(), name="brewery_list"),
    path("<int:pk>/", views.BreweryDetail.as_view(), name="brewery_detail"),
    path("create/", views.BreweryCreate.as_view(), name="brewery_create"),
    path("<int:pk>/image/", views.ImageCreate.as_view(), name="image_create"),
]

app/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path("", include("index.urls"), name="index"),
    path("admin/", admin.site.urls),
    path("beer/", include("beer.urls"), name="beer"),
    path("brewery/", include("brewery.urls"), name="brewery"),
    path("location/", include("location.urls"), name="location"),
    path("user/", include("user.urls"), name="user"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Brews and Beers Admin"
admin.site.site_title = "Brews and Beers"
admin.site.index_title = "Admin Dashboard"

app/index/urls.py
from django.urls import path

from . import views

app_name = "index"

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("search/", views.search, name="search"),
]

app/user/urls.py
from django.urls import path

from . import views

app_name = "user"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("password_reset", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("<int:pk>/", views.UserDetail.as_view(), name="user_detail"),
]

app/templates/partials/footer.html
<footer class="container mt-5 py-3 my-4 border-top">
  <div class="d-flex flex-wrap justify-content-between align-items-center">
    <p class="col-md-4 mb-0">© 2023 Brews and Beers</p>
    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item"><a href="{% url 'index:index' %}" class="nav-link px-2 text-body-secondary">Home</a></li>
      <li class="nav-item"><a href="{% url 'user:register' %}" class="nav-link px-2 text-body-secondary">Register</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Privacy</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Contact</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
    </ul>
  </div>
</footer>

app/templates/partials/header.html
{% load static %}
<header class="p-3">
  <div class="container-fluid">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="{% url 'index:index' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-decoration-none">
        <img class="bi me-2" width="40" height="40" src="{% static 'img/reward.png' %}" alt="Brews and Beers">
        <h4 class="text-warning">Brews and Beers</h4>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto">
        <li><a href="{% url 'brewery:brewery_list' %}" class="nav-link px-2 text-secondary">Breweries</a></li>
        <li><a href="{% url 'beer:beer_list' %}" class="nav-link px-2 text-secondary">Beers</a></li>
      </ul>

      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'index:search' %}" method="get">
        {% csrf_token %}
        <input type="search" class="form-control" placeholder="Search..." aria-label="Search" name="search">
      </form>

      <div class="text-end">
      {% if user.is_authenticated %}
        <div class="dropdown text-end">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{% static 'img/user.png' %}" alt="mdo" width="32" height="32" class="rounded-circle">
          </a>
          <ul class="dropdown-menu text-small" style="">
            <li><a class="dropdown-item" href="{% url 'user:profile' %}">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a></li>
          </ul>
        </div>
      {% else %}
        <a class="btn btn-outline-warning me-2" href="{% url 'user:login' %}">Login</a>
      {% endif %}
      </div>
    </div>
  </div>
</header>